name: Data download

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  download-data:
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
        #if: github.event.schedule == '0 0 * * *'
        # with:
        # command: npm run download
      - name: Install dependencies
        run: npm install
      - name: Run npm task
        run: npm run download-saas
      - name: Git add
        run: git add -A
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Automated commit
          commit_options: "--no-verify --signoff"
          file_pattern: "*.json"
          dd_options: '-u'
          repository: .
          status_options: "--untracked-files=no"
          # add_option: "-u"
          push_options: "--force"
          skip_fetch: true
          skip_checkout: true
